### PR TITLE
Set flag to determine if state was available

### PR DESCRIPTION
**Pull request by sam-dixon**
This adds an additional element to the object returned by `getEditorState`. If the state was successfully obtained, set it to True. Otherwise, it is returned as False.

NB: I took this approach since you can't set `std::string` objects to `NULL`. This allows us to differentiate between the state being empty and the state being impossible to reach.

### CODE REVIEW

**Review by tmacwill — CHANGES_REQUESTED** [review]
thanks for doing this! agree this is the best approach for communicating this state. what do you think about flipping `stateAvailable` to `error`? there's a common node.js pattern where an `error` field is returned if something went wrong, and so we could be consistent with that.

**Comment by sam-dixon** [comment]
I flipped `stateAvailable` to `error` and changed the client where necessary too.

**Review by tmacwill — APPROVED** [review]
awesome, thanks!

**Comment by tmacwill** [comment]
I manually merged this PR into #5 since it depended on this one, so closing this out!

**Pull request closed without merging**
